### PR TITLE
2.x: Fix refCount termination-reconnect race

### LINKED ISSUE #6185: Possible concurrency issue with .refCount()? (2.2.0)
First, I want to thank you for this wonderful library which I gladly use in many professional applications!

While I was writing a component for one of our company applications, I wrote a multithreaded stress test, because the component itself introduces shared state. Sometimes the test failed. Of course, I suspected my component to be the culprit. After further investigation I could completely rule out my own component and still reproduce the problem. 
I think there could be a problem with the `refCount()` operator.

Less words, more code:

The problem is reproducible with the following unit test (well, at least as reproducible as a test in a multithreaded manner can be...)

```
public void replayRefCountShallBeThreadSafe() {
        for (int i = 0; i < 10000; i++) {
            Observable<Object> observable = Observable.just(new Object()).replay(1).refCount();

            TestObserver<Object> observer1 = observable
                    .subscribeOn(Schedulers.io())
                    .test();

            TestObserver<Object> observer2 = observable
                    .subscribeOn(Schedulers.io())
                    .test();

            assertThat(observer1.awaitTerminalEvent(5, TimeUnit.SECONDS), is(true));
            assertThat(observer2.awaitTerminalEvent(5, TimeUnit.SECONDS), is(true));
        }
}
```

As you can see, I am repeating the logic 10000 times. This (mostly) guarantees that the test fails on my environment. One of the observers does NOT receive the completed event and therefore the `awaitTerminalEvent` times out.

On the other hand, the following unit test where I manually `.connect()` the `ConnectableObservable`  returned vom `.replay(1)` passes:

```
public void replayShallBeThreadSafe() {
        for (int i = 0; i < 10000; i++) {
            ConnectableObservable<Object> observable = Observable.just(new Object()).replay(1);
            Disposable connection = observable.connect();

            TestObserver<Object> observer1 = observable
                    .subscribeOn(Schedulers.io())
                    .test();

            TestObserver<Object> observer2 = observable
                    .subscribeOn(Schedulers.io())
                    .test();

            assertThat(observer1.awaitTerminalEvent(5, TimeUnit.SECONDS), is(true));
            assertThat(observer2.awaitTerminalEvent(5, TimeUnit.SECONDS), is(true));
            connection.dispose();
        }
}
```

Please tell me if I am missing something...

Version: RxJava 2.2.0
Tests are JUnit tests, with hamcrest assertions.

Thanks!

### PR DESCRIPTION
**Pull request by akarnokd**
This PR modifies the `refCount` operator (in both `Flowable` and `Observable` types) to avoid certain termination-reconnection races.

The original race could happen when the refCounted source terminated at the same time as new observers arrived, leaving those new observers hanging as they practically joined a dying connection and got possibly undercut by the `dispose` call.

The change involve a new internal interface `ResettableConnection` that will allow resetting the connection object inside the connectable source if it is equal to the connection object known by the initiator of the original `connect` call.

Fixes #6185

### CODE REVIEW

File: src/main/java/io/reactivex/internal/disposables/ResettableConnectable.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+/**
+ * Interface allowing conditional resetting of connections in {@link ConnectableObservable}s
+ * and {@link ConnectableFlowable}s.
+ * @since 2.2.2 - experimental
+ */
+@Experimental
+public interface ResettableConnectable {
+
+    /**
+     * Reset the connectable if the current internal connection object is the
```
Comment (vanniktech) [inline src/main/java/io/reactivex/internal/disposables/ResettableConnectable.java]: Find it hard to read and follow. Could we link the param in here so it's understandable what's the internal and what's the provided object?

**Review by vanniktech — APPROVED** [review]

File: src/main/java/io/reactivex/internal/disposables/ResettableConnectable.java (hunk 1 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/internal/disposables/ResettableConnectable.java]: Changed the description.

**Review by vanniktech — APPROVED** [review]
Much better.

**Review by davidmoten — COMMENTED** [review]
LGTM, thanks

**Comment by davidmoten** [comment]
Thanks for the fix @akarnokd and the report @BernhardReu. A release in the next couple of weeks with this change would be very welcome (`.share` is a critical path for me). /cc @SuperEvenSteven @philipgroom.

**Comment by akarnokd** [comment]
@davidmoten Sure. #6194

**Comment by jhansche** [comment]
@akarnokd This seems to fix the issue for `.replay().refCount()`, but I'm seeing the same test fail intermittently with `.publish().refCount()` (aka `share()`):

```
    @Test
    fun `test refcount race conditions`() {
        for (i in 0 until 10_000) {
            val observable = Observable.just(1).publish().refCount()

            val observer1 = observable
                .subscribeOn(Schedulers.io())
                .test()

            val observer2 = observable
                .subscribeOn(Schedulers.io())
                .test()

            observer1
                .withTag("observer1 $i")
                .awaitDone(5, TimeUnit.SECONDS)
                .assertResult(1)

            observer2
                .withTag("observer2 $i")
                .awaitDone(5, TimeUnit.SECONDS)
                .assertResult(1)
        }
    }
```

The actual failure is obviously unpredictable due to the race conditions, but it usually fails pretty early.  In this case, it failed at `i=14`:

```
java.lang.AssertionError: Value count differs; expected: 1 [1] but was: 0 [] (latch = 1, values = 0, errors = 0, completions = 0, timeout!, disposed!, tag = observer2 14)
Expected :1 [1] 
Actual   :0 [] (latch = 1, values = 0, errors = 0, completions = 0, timeout!, disposed!, tag = observer2 14)
```

**Comment by akarnokd** [comment]
@jhansche It is possible one of the observers connect right between onNext and onComplete, thus it may not receive the value. However, they should both complete, no timeout. I put in a fresh issue #6501 and will investigate further tomorrow.
