### PR TITLE
2.x: Fix refCount eager disconnect not resetting the connection

### LINKED ISSUE #6296: 2.x: refCount doesn't reset its source if one of its subscribers cancels immediately
The following tests fail because the cancel/dispose from the downstream comes before the actual connection is established which leaves the connectable source in a disposed state, refusing to take in new subscribers/observers:

```java
@Test
public void test() {
    BehaviorSubject<Integer> subject = BehaviorSubject.create();

    Observable<Integer> observable = subject
            .replay(1)
            .refCount();

    observable.takeUntil(Observable.just(1)).test();

    subject.onNext(2);

    observable.take(1).test().assertResult(2);
}


@Test
public void test2() {
    BehaviorProcessor<Integer> processor = BehaviorProcessor.create();

    Flowable<Integer> flowable = processor
            .replay(1)
            .refCount();

    // This line causes the test to fail.
    flowable.takeUntil(Flowable.just(1)).test();

    processor.onNext(2);

    flowable.take(1).test().assertResult(2);
}
```

### PR DESCRIPTION
**Pull request by akarnokd**
This PR fixes the case when an observer/subscriber disposes/cancels immediately upon subscribing to a `refCount` operator before it establishes the connection and ends up with a disposed but non-reset connection, preventing further interactions with the connectable source.

The fix is to detect this case and reset the connection when the `connect()` method signals the dispose handler.

Both `ConnectableFlowable.refCount` and `ConnectableFlowable.refCount` is affected.

Fixes: #6296

### CODE REVIEW

**Review by vanniktech — APPROVED** [review]

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java [hunk 1]
```diff
@@ -1394,4 +1394,20 @@ public void timeoutDisposesSource() {
...
+
+    @Test
+    public void disconnectBeforeConnect() {
+        BehaviorProcessor<Integer> processor = BehaviorProcessor.create();
+
+        Flowable<Integer> flowable = processor
+                .replay(1)
+                .refCount();
+
+        // This line causes the test to fail.
```
Comment (artem-zinnatullin) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java]: nit: "caused"

File: src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java [hunk 2]
```diff
@@ -1345,4 +1345,19 @@ public void timeoutDisposesSource() {
...
+
+    @Test
+    public void disconnectBeforeConnect() {
+        BehaviorSubject<Integer> subject = BehaviorSubject.create();
+
+        Observable<Integer> observable = subject
+                .replay(1)
+                .refCount();
+
+        observable.takeUntil(Observable.just(1)).test();
```
Comment (artem-zinnatullin) [inline src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java:1357]: For consistency, this line either needs same comment as flowable test, or it should be removed from flowable test

**Review by artem-zinnatullin — APPROVED** [review]

File: src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java (hunk 2 above)
Comment (akarnokd) [reply src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java:1357]: Removed from the other place.

**Review by artem-zinnatullin — APPROVED** [review]
