### PR TITLE
2.x: Check isdisposed before emitting in SingleFromCallable

### LINKED ISSUE #5742: 2.x: SingleFromCallable doesn't check isDisposed before calling onError or onSuccess.
I was investigating a bug and I noticed that `SingleFromCallable` doesn't check `isDisposed()` before calling `onError` or `onSuccess` when comparing it to `ObservableFromCallable`.

Should it be checking `isDisposed()`? If not, why not? Or is this a bug?

My code example where I'm getting this error is Android based:
I have a HomePresenter with this code:
```
void setActivity(Activity activity) {
	Timber.d(“HomePresenter attachActivity”);
	this.activity = activity;
}
```

```
void onStart() {
	Timber.d(“HomePresenter onStart”);
	disposables.add(api.getEmail()
		.subscribeOn(Schedulers.io())
		.observeOn(AndroidSchedulers.mainThread())
		.subscribe(email -> {
			Timber.d(“email was %s”, email);
			activity.setEmail(email);
		})
	);
```
```
void onStop() {
	Timber.d(“HomePresenter onStop”);
	disposables.clear();
	activity = null;
}
```

in the logs I see:
```
Lifecycle onStart HomeActivity
HomePresenter attachActivity
HomePresenter onStart
Lifecycle onStop HomeActivity
HomePresenter onStop
email was foo@bar.com
NullPointerException: attempt to invoke virtual method Activity.setEmail(String) on null object reference
```

It seems the subscription to the observable was cleared before the `onSuccess` method was called.

Or maybe I'm missing something else completely, anyways, thanks for the help :)

### PR DESCRIPTION
**Pull request by runningcode**
Previously SingleFromCallable did not check if the subscriber was
unsubscribed before emitting onSuccess or onError. This fixes that
behavior and adds tests to SingleFromCallable, CompletableFromCallable,
and MaybeFromCallable.

Fixes #5742

### CODE REVIEW

**Review by akarnokd — APPROVED** [review]

File: src/main/java/io/reactivex/internal/operators/single/SingleFromCallable.java [hunk 1]
```diff
@@ -28,20 +32,29 @@ public SingleFromCallable(Callable<? extends T> callable) {
...
+            return;
+        }
+        T value;
 
-        s.onSubscribe(EmptyDisposable.INSTANCE);
         try {
-            T v = callable.call();
-            if (v != null) {
-                s.onSuccess(v);
+            value = ObjectHelper.requireNonNull(callable.call(), "Callable returned null");
```
Comment (akarnokd) [inline src/main/java/io/reactivex/internal/operators/single/SingleFromCallable.java]: You got the error message wrong.

[Travis CI](https://travis-ci.org/ReactiveX/RxJava/builds/307154950#L607)

**Review by vanniktech — APPROVED** [review]

File: src/main/java/io/reactivex/internal/operators/single/SingleFromCallable.java (hunk 1 above)
Comment (runningcode) [reply src/main/java/io/reactivex/internal/operators/single/SingleFromCallable.java]: 👍 fixed now :)

**Comment by akarnokd** [comment]
Could you please restore the code coverage of `SingleFromCallable`? The new logic introduced a bunch of code paths that need testing.

**Comment by runningcode** [comment]
Sounds good. I added a few tests by copying the logic from `ObservableFromCallable`.
