### PR TITLE
2.x: Fix buffer(open, close) not disposing indicators properly

### LINKED ISSUE #5809: 2.x: FlowableBufferBoundary doesn't stop opening new windows in overlapping case
Consider an `open` source for `FlowableBufferBoundary` that never stops, like a `Flowable.interval`. In the case where the buffer opening and closing signal overlap, the opening of new windows never stops even when the source of data completes.

The second test below times out as a result:

```java
@Test
    public void bufferedCanCompleteIfOpenNeverCompletesDropping() {
        Flowable.range(1, 200)
                .zipWith(Flowable.interval(5, TimeUnit.MILLISECONDS),
                        new BiFunction<Integer, Long, Integer>() {
                            @Override
                            public Integer apply(Integer integer, Long aLong) {
                                return integer;
                            }
                        })
                .buffer(Flowable.interval(0,200, TimeUnit.MILLISECONDS),
                        new Function<Long, Publisher<?>>() {
                            @Override
                            public Publisher<?> apply(Long a) {
                                return Flowable.just(a).delay(100, TimeUnit.MILLISECONDS);
                            }
                        })
                .test()
                .assertSubscribed()
                .awaitDone(3, TimeUnit.SECONDS)
                .assertComplete();
    }

    @Test
    public void bufferedCanCompleteIfOpenNeverCompletesOverlapping() {
        Flowable.range(1, 200)
                .zipWith(Flowable.interval(5, TimeUnit.MILLISECONDS),
                        new BiFunction<Integer, Long, Integer>() {
                            @Override
                            public Integer apply(Integer integer, Long aLong) {
                                return integer;
                            }
                        })
                .buffer(Flowable.interval(0,100, TimeUnit.MILLISECONDS),
                        new Function<Long, Publisher<?>>() {
                            @Override
                            public Publisher<?> apply(Long a) {
                                return Flowable.just(a).delay(200, TimeUnit.MILLISECONDS);
                            }
                        })
                .test()
                .assertSubscribed()
                .awaitDone(3, TimeUnit.SECONDS)
                .assertComplete();
    }
```

### PR DESCRIPTION
**Pull request by akarnokd**
The PR fixes the resource management in the `buffer` operator that uses other reactive sources to indicate when a buffer starts and ends. Both `Flowable` and `Observable` implementations had to be fixed.

Fixes: #5809

### CODE REVIEW

**Comment by simonbasle** [comment]
@akarnokd let me know if I understand the spirit of this PR on `FlowableBufferBoundary`:

1. avoids keeping reference to / tracking buffers in subscribers other than the main
2. cancel source on open subscriber completion (if it completes and the last buffer's close publisher has completed, subscribers will have size 0 and we can safely cancel upstream as no new buffer will open at this point)
3. in main, distinguish a open subscriber error from a close subscriber error (due to 1., the later needs associated buffer cleanup)

Is that correct/exhaustive?

**Comment by akarnokd** [comment]
> avoids keeping reference to / tracking buffers in subscribers other than the main

Yes.

> cancel source on open subscriber completion (if it completes and the last buffer's close publisher has completed, subscribers will have size 0 and we can safely cancel upstream as no new buffer will open at this point

Yes.

> in main, distinguish a open subscriber error from a close subscriber error (due to 1., the later needs associated buffer cleanup

No. If the `openError` or `closeError` is fired, both should cancel the main source, cancel the subscribers other than themselves, clean the buffer and then report the error. They could be converted into a common method of `boundsError(Disposable d, Throwable ex)`.

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java [hunk 1]
```diff
@@ -98,214 +119,340 @@ public void onSubscribe(Subscription s) {
...
-            for (U u : list) {
-                q.offer(u);
+                Map<Long, C> bufs = buffers;
+                if (bufs == null) {
+                    return;
+                }
+                for (C b : bufs.values()) {
+                    queue.offer(b);
+                }
+                bufs = null;
```
Comment (simonbasle) [inline src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: shouldn't this be `buffers = null`?

Comment (akarnokd) [reply src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: Yes, fixed. Also combined the error methods and changed to LinkedHashMap so that the final open buffers in `onComplete` remain in their order they were opened.

**Review by simonbasle — APPROVED** [review]
got it, looking better with the buffers null-out and the mutualized `boundaryError` 👍

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java [hunk 2]
```diff
@@ -98,214 +119,325 @@ public void onSubscribe(Subscription s) {
...
+                        } else
+                        if (q.isEmpty()) {
+                            a.onComplete();
+                            return;
+                        }
+                    }
+                }
+
+                emitted = e;
+                missed = addAndGet(-missed);
```
Comment (davidmoten) [inline src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: `requested` not getting reduced by `emitted`?

**Review by davidmoten — COMMENTED** [review]
gave quick scan only

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java (hunk 2 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: No longer necessary in these type of drain loops. `requested` can only grow and the `emitted` will follow it separately. This saves an atomic decrement here.

Comment (davidmoten) [reply src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: ok, beaut

**Review by davidmoten — APPROVED** [review]

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java [hunk 3]
```diff
@@ -98,214 +119,325 @@ public void onSubscribe(Subscription s) {
...
+                done = true;
+            }
+            drain();
+        }
 
-            BufferCloseSubscriber<T, U, Open, Close> bcs = new BufferCloseSubscriber<T, U, Open, Close>(b, this);
-            resources.add(bcs);
+        void boundaryError(Disposable subscriber, Throwable ex) {
+            SubscriptionHelper.cancel(upstream);
+            subscribers.delete(subscriber);
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java:242]: Can we just `dispose()` all subscribers here and remove `dispose()` call below?

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java [hunk 4]
```diff
@@ -98,214 +119,325 @@ public void onSubscribe(Subscription s) {
...
+                    }
+
+                    if (done) {
+                        if (errors.get() != null) {
+                            q.clear();
+                            Throwable ex = errors.terminate();
+                            a.onError(ex);
+                            return;
+                        } else
+                        if (q.isEmpty()) {
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: nit: formatting, this line typically goes on the same line with `else`

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java [hunk 5]
```diff
@@ -98,214 +119,325 @@ public void onSubscribe(Subscription s) {
...
+        void open(Open token) {
+            Publisher<? extends Close> p;
+            C buf;
+            try {
+                buf = ObjectHelper.requireNonNull(bufferSupplier.call(), "The bufferSupplier returned a null Collection");
+                p = ObjectHelper.requireNonNull(bufferClose.apply(token), "The bufferClose returned a null Publisher");
+            } catch (Throwable ex) {
+                Exceptions.throwIfFatal(ex);
+                SubscriptionHelper.cancel(upstream);
+                if (errors.addThrowable(ex)) {
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: if/else block seems to be exact same as `onError()`, let's just call it here?

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java (hunk 3 above)
Comment (artem-zinnatullin) [reply src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java:242]: Same in Observable version

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java [hunk 6]
```diff
@@ -98,214 +119,325 @@ public void onSubscribe(Subscription s) {
...
+            }
+            drain();
+        }
 
-            BufferCloseSubscriber<T, U, Open, Close> bcs = new BufferCloseSubscriber<T, U, Open, Close>(b, this);
-            resources.add(bcs);
+        void boundaryError(Disposable subscriber, Throwable ex) {
+            SubscriptionHelper.cancel(upstream);
+            subscribers.delete(subscriber);
+            if (errors.addThrowable(ex)) {
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: if/else block seems to be exact same as `onError()`, let's just call it here?

Comment (artem-zinnatullin) [reply src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java]: Same in Observable version

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java [hunk 7]
```diff
@@ -2074,4 +2076,364 @@ public void run() throws Exception {
 
         assertEquals(0, counter.get());
     }
+
+    @Test
+    @SuppressWarnings("unchecked")
+    public void boundaryOpenCloseDisposedOnComplete() {
+        PublishProcessor<Integer> pp0 = PublishProcessor.create();
```
Comment (artem-zinnatullin) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java]: nit: `upstream`

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java [hunk 8]
```diff
@@ -2074,4 +2076,364 @@ public void run() throws Exception {
...
+
+        PublishProcessor<Integer> pp1 = PublishProcessor.create();
```
Comment (artem-zinnatullin) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java]: nit: `openingIndicator`

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java [hunk 9]
```diff
@@ -2074,4 +2076,364 @@ public void run() throws Exception {
...
+
+        PublishProcessor<Integer> pp2 = PublishProcessor.create();
```
Comment (artem-zinnatullin) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java]: nit: `closingIndicator`

Comment (artem-zinnatullin) [reply src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java]: and same in some tests below

File: src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java (hunk 3 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundary.java:242]: It avoids disposing the caller which is known to have reached its terminal state.

**Review by artem-zinnatullin — APPROVED** [review]
lgtm

**Review by vanniktech — COMMENTED** [review]
👍
