### PR TITLE
1.x: fix assembly tracking replacing original exception

### LINKED ISSUE #4212: RxJavaHooks.enableAssemblyTracking() breaks error handling
Problem:

If user enables assembly tracking then **ALL** exceptions get wrapped into `AssemblyStackTraceException` which breaks all error handling code that expects particular exceptions.

Solution:

Do not change type of original exception and modify its stacktrace directly. I'll work on that soon, both for 1.x and 2.x.

// Spent an hour today trying to figure out what was causing app misbehave, glad we have `git bisect`, was very surprised to see commit where I enabled assembly tracking…

### PR DESCRIPTION
**Pull request by akarnokd**
Modify the assembly tracking logic to not replace the exception flowing through but to attach the tracking exception to the end of the causal chain (if possible).

Fixes #4212

### CODE REVIEW

**Comment by stevegury** [comment]
👍

File: src/main/java/rx/exceptions/AssemblyStackTraceException.java [hunk 1]
```diff
@@ -49,4 +42,48 @@ public AssemblyStackTraceException(String message) {
     public synchronized Throwable fillInStackTrace() { // NOPMD 
         return this;
     }
+    
+    /**
+     * Finds an empty cause slot and assigns itself to it.
+     * @param exception the exception to start from
+     */
+    public void attach(Throwable exception) {
```
Comment (artem-zinnatullin) [inline src/main/java/rx/exceptions/AssemblyStackTraceException.java]: `attachTo`, otherwise it looks like you're attaching `exception` to `this` while in fact it's vice versa

File: src/main/java/rx/exceptions/AssemblyStackTraceException.java [hunk 2]
```diff
@@ -49,4 +42,48 @@ public AssemblyStackTraceException(String message) {
...
+        }
+    }
+    
+    /**
+     * Locate the first AssemblyStackTraceException in the causal chain of the
+     * given Throwable (or it if it's one).
+     * @param e the input throwable 
+     * @return the AssemblyStackTraceException located or null if not found 
+     */
+    public static AssemblyStackTraceException find(Throwable e) {
```
Comment (artem-zinnatullin) [inline src/main/java/rx/exceptions/AssemblyStackTraceException.java:74]: this is test method, please move it to tests

**Comment by artem-zinnatullin** [comment]
👍

File: src/main/java/rx/exceptions/AssemblyStackTraceException.java (hunk 2 above)
Comment (akarnokd) [inline src/main/java/rx/exceptions/AssemblyStackTraceException.java:74]: No, this let's one get this specific exception, for example, in a live app that has a tracking enabled for diagnostic purposes.

Comment (artem-zinnatullin) [inline src/main/java/rx/exceptions/AssemblyStackTraceException.java:74]: okay… not sure that anybody will ever look here though
