### PR TITLE
3.x: Fix mergeWith not cancelling the other source if the main errors

### LINKED ISSUE #6597: using Observable#mergeWith(CompletableSource), upstream occurs an error, but the ComletableSource won't be disposed
using Observable#mergeWith(CompletableSource), upstream occurs an error, but the ComletableSource won't be disposed.

```java
Observable.create(new ObservableOnSubscribe<Object>() {
    @Override
    public void subscribe(ObservableEmitter<Object> emitter) throws Exception {
        Schedulers.io().scheduleDirect(
            () -> emitter.tryOnError(new Throwable("occurs error")),
            1, TimeUnit.SECONDS);
        }
    })
    .mergeWith(
        Completable.create(emmit ->
            emmit.setCancellable(() -> System.out.println("mergeWith dispose"))
         )
         .doOnSubscribe(dis -> System.out.println("mergeWith doOnSubscribe"))
    )
    .subscribe(ob -> {}, System.out::println);
```
the result is :
```
mergeWith doOnSubscribe
java.lang.Throwable: occurs error
```

but if add 'toObservable()' 
```
Observable.create(new ObservableOnSubscribe<Object>() {
            @Override
            public void subscribe(ObservableEmitter<Object> emitter) throws Exception {
                Schedulers.io().scheduleDirect(() -> emitter.tryOnError(new Throwable("occurs error")), 1, TimeUnit.SECONDS);
            }
        })
                .mergeWith(Completable.create(emmit ->
                        emmit.setCancellable(() -> System.out.println("mergeWith dispose")))
                        .doOnSubscribe(dis -> System.out.println("mergeWith doOnSubscribe")).toObservable())
                .subscribe(ob -> {}, System.out::println);
```

the result is: 
```
mergeWith doOnSubscribe
mergeWith dispose
java.lang.Throwable: occurs error
```

The 'dispose' will be invoked。
In case of first,it will produce a memory leak.
Is that a bug?

### PR DESCRIPTION
**Pull request by akarnokd**
The `mergeWith` implementations' `onError` (called by the main source) cancelled the main source instead of cancelling the other source. This mistake affects all 2 x 3 overloads of the operator.

Fixes #6597

### CODE REVIEW

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletableTest.java [hunk 1]
```diff
@@ -137,4 +137,40 @@ public void run() {
...
+        pp.onError(new TestException());
+
+        ts.assertFailure(TestException.class);
+
+        assertFalse("main has observers!", pp.hasSubscribers());
+        assertFalse("other has observers", cs.hasObservers());
+    }
+
+    @Test
+    public void cancelMainOnOhterError() {
```
Comment (Mikey-Burns) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletableTest.java]:
```suggestion
    public void cancelMainOnOtherError() {
```

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybeTest.java [hunk 2]
```diff
@@ -402,4 +402,40 @@ public void onNext(Integer t) {
...
+        pp.onError(new TestException());
+
+        ts.assertFailure(TestException.class);
+
+        assertFalse("main has observers!", pp.hasSubscribers());
+        assertFalse("other has observers", ms.hasObservers());
+    }
+
+    @Test
+    public void cancelMainOnOhterError() {
```
Comment (Mikey-Burns) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybeTest.java]:
```suggestion
    public void cancelMainOnOtherError() {
```

File: src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingleTest.java [hunk 3]
```diff
@@ -398,4 +398,40 @@ public void onNext(Integer t) {
...
+        pp.onError(new TestException());
+
+        ts.assertFailure(TestException.class);
+
+        assertFalse("main has observers!", pp.hasSubscribers());
+        assertFalse("other has observers", ss.hasObservers());
+    }
+
+    @Test
+    public void cancelMainOnOhterError() {
```
Comment (Mikey-Burns) [inline src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingleTest.java]:
```suggestion
    public void cancelMainOnOtherError() {
```

File: src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletableTest.java [hunk 4]
```diff
@@ -136,4 +136,40 @@ protected void subscribeActual(Observer<? super Integer> observer) {
...
+        ps.onError(new TestException());
+
+        to.assertFailure(TestException.class);
+
+        assertFalse("main has observers!", ps.hasObservers());
+        assertFalse("other has observers", cs.hasObservers());
+    }
+
+    @Test
+    public void cancelMainOnOhterError() {
```
Comment (Mikey-Burns) [inline src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletableTest.java]:
```suggestion
    public void cancelMainOnOtherError() {
```

File: src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybeTest.java [hunk 5]
```diff
@@ -273,4 +273,39 @@ public void onNext(Integer t) {
...
+        ps.onError(new TestException());
+
+        to.assertFailure(TestException.class);
+
+        assertFalse("main has observers!", ps.hasObservers());
+        assertFalse("other has observers", ms.hasObservers());
+    }
+
+    @Test
+    public void cancelMainOnOhterError() {
```
Comment (Mikey-Burns) [inline src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybeTest.java]:
```suggestion
    public void cancelMainOnOtherError() {
```

File: src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingleTest.java [hunk 6]
```diff
@@ -264,4 +264,40 @@ public void onNext(Integer t) {
...
+        ps.onError(new TestException());
+
+        to.assertFailure(TestException.class);
+
+        assertFalse("main has observers!", ps.hasObservers());
+        assertFalse("other has observers", ss.hasObservers());
+    }
+
+    @Test
+    public void cancelMainOnOhterError() {
```
Comment (Mikey-Burns) [inline src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingleTest.java]:
```suggestion
    public void cancelMainOnOtherError() {
```

**Review by Mikey-Burns — CHANGES_REQUESTED** [review]
Minor typo in some of the test method names.  The rest of the fix looks great.

**Review by vanniktech — APPROVED** [review]

**Review by Mikey-Burns — APPROVED** [review]
