### PR TITLE
CachedThreadScheduler should wait until the previous action (if any) …

### LINKED ISSUE #4230: Schedulers.io() reuses blocked threads
Some actions are not interruptible. Since Schedulers.io() reuses threads after unsubscribe, a previous uninterruptible action might block execution of new actions, causing unexpected delays or in some cases, deadlocks.

### PR DESCRIPTION
**Pull request by csabakos-zz**
…completes before releasing a worker to the pool. Fixes #4230.

### CODE REVIEW

File: src/main/java/rx/internal/schedulers/CachedThreadScheduler.java [hunk 1]
```diff
@@ -190,7 +190,14 @@ public Worker createWorker() {
         public void unsubscribe() {
             if (once.compareAndSet(false, true)) {
                 // unsubscribe should be idempotent, so only do this once
-                pool.release(threadWorker);
+
+                // Release the worker _after_ the previous action (if any) has completed
+                threadWorker.schedule(new Action0() {
```
Comment (akarnokd) [inline src/main/java/rx/internal/schedulers/CachedThreadScheduler.java]: EventLoopWorker can implement Action0 and schedule itself to release.

Comment (csabakos-zz) [inline src/main/java/rx/internal/schedulers/CachedThreadScheduler.java]: @akarnokd What would be the advantage of doing so?

Comment (akarnokd) [inline src/main/java/rx/internal/schedulers/CachedThreadScheduler.java]: It saves an allocation; I believe io() workers are used and unsubscribed frequently enough to save on this allocation.

Comment (csabakos-zz) [inline src/main/java/rx/internal/schedulers/CachedThreadScheduler.java]: Makes sense, let me change it.

**Comment by akarnokd** [comment]
:+1: 

Given a misbehaving task, this at least prevents other work to be scheduled on the same pool.
