### PR TITLE
fix #5468: eager hooks onError call

### LINKED ISSUE #5468: 1.x Single#flatMapCompletable calls hooks onError when mapping to an error completeable
If you flatmap a Single into a Completeable, and the Completeable is an error, you will have the exception passed into the RxJavaHooks.onError global catch function as well as ending up with the Completeable Error you expect to see.

I have managed to get is down to the follow test case highlighting the problem,

```
@Test
    public void flatMapCompletableErrorCallsHooksErrorHandler() {
        AtomicBoolean wasHooksHandlerCalled = new AtomicBoolean();
        RxJavaHooks.setOnError(t -> wasHooksHandlerCalled.set(true));

        Completable c3  = Single.just(1)
                .flatMapCompletable(i -> Completable.error(new RuntimeException("some exception")));

        c3.get();

        assertThat(wasHooksHandlerCalled.get(), is(false)); //fails
    }
```

I did some digging and I think this is happening due to a bug in SafeCompletableSubscriber, where it calls  RxJavaHooks.onError(e) before it attempts to pass the error in to the wrapped subscribers onError method. ie

```
public void onError(Throwable e) {
        RxJavaHooks.onError(e);
        if (done) {
            return;
        }
        done = true;
        try {
            actual.onError(e);
        } catch (Throwable ex) {
            Exceptions.throwIfFatal(ex);

            throw new OnErrorFailedException(new CompositeException(e, ex));
        }
    }
```

Looking at SafeSubscriber, I think the correct behaviour is to only have the call to ` RxJavaHooks.onError(e);` happen inside the catch block, as no exception has leaked at the point where it is currently being called.

### PR DESCRIPTION
**Pull request by DeepSpawn**
Move the call to RxJavaHooks into the catch block, so we only report and it if the underlying subscriber throws in its onError method.

This brings its behaviour in line with that of SafeSubscriber

### CODE REVIEW

**Comment by DeepSpawn** [comment]
Not sure if this change warrants a unit test, but I am happy to add them if you think it is necessary

File: src/main/java/rx/observers/SafeCompletableSubscriber.java [hunk 1]
```diff
@@ -54,7 +54,6 @@ public void onCompleted() {
 
     @Override
     public void onError(Throwable e) {
-        RxJavaHooks.onError(e);
         if (done) {
             return;
```
Comment (akarnokd) [inline src/main/java/rx/observers/SafeCompletableSubscriber.java]: You should have moved it here.

**Review by akarnokd — CHANGES_REQUESTED** [review]

File: src/main/java/rx/observers/SafeCompletableSubscriber.java [hunk 2]
```diff
@@ -63,6 +62,7 @@ public void onError(Throwable e) {
             actual.onError(e);
         } catch (Throwable ex) {
             Exceptions.throwIfFatal(ex);
+            RxJavaHooks.onError(e);
```
Comment (DeepSpawn) [inline src/main/java/rx/observers/SafeCompletableSubscriber.java]: @akarnokd  so this should be in if(done) only?

Comment (akarnokd) [reply src/main/java/rx/observers/SafeCompletableSubscriber.java]: Yes.

**Review by vanniktech — APPROVED** [review]

**Review by akarnokd — APPROVED** [review]
