### PR TITLE
3.x: Fix scheduled tasks' fatal exception behavior

### LINKED ISSUE #6954: 3.x: Exceptions will be swallowed when schedulers are involved
In general, exceptions should never be swallowed and should be handled somewhere, eg., catch clause or uncaught exception handlers of threads.

As to RxJava, exceptions are expected to be handled at:
- observer's onError(), or
- RxJava exception handler (RxJavaPlugins.onError()), or
- thread's uncaught exception handler (eg., exceptions thrown by Exceptions.throwIfFatal()), 

and not to be magically swallowed somewhere.

This is true in most situations, but is broken when schedulers are involved. That is, the following tests will fail:

**(Test 1) Exceptions from observables are swallowed:**

    @Test
    public void exceptionFromObservableShouldNotBeSwallowed() throws Exception {
        // Exceptions, fatal or not, should be handled by
        // #1 observer's onError(), or
        // #2 RxJava exception handler, or
        // #3 thread's uncaught exception handler,
        // and should not be swallowed.
        try {
            CountDownLatch latch = new CountDownLatch(1);

            // #3 thread's uncaught exception handler
            Scheduler computationScheduler = new ComputationScheduler(new ThreadFactory() {
                @Override
                public Thread newThread(Runnable r) {
                    Thread t = new Thread(r);
                    t.setUncaughtExceptionHandler((thread, throwable) -> {
                        latch.countDown();
                    });
                    return t;
                }
            });

            // #2 RxJava exception handler
            RxJavaPlugins.setErrorHandler(h -> {
                latch.countDown();
            });

            // #1 observer's onError()
            Observable.create(s -> {

                s.onNext(1);

                if (true) {
                    throw new OutOfMemoryError();
                }

                s.onComplete();

            }).subscribeOn(computationScheduler)
            .subscribe(v -> {
            }, e -> {
                latch.countDown();
            });

            assertTrue(latch.await(2, TimeUnit.SECONDS));
        } finally {
            RxJavaPlugins.reset();
        }
    }

**(Test 2) Exceptions from observers are swallowed:**

    @Test
    public void exceptionFromObserverShouldNotBeSwallowed() throws Exception {
        // Exceptions, fatal or not, should be handled by
        // #1 observer's onError(), or
        // #2 RxJava exception handler, or
        // #3 thread's uncaught exception handler,
        // and should not be swallowed.
        try {
            CountDownLatch latch = new CountDownLatch(1);

            // #3 thread's uncaught exception handler
            Scheduler computationScheduler = new ComputationScheduler(new ThreadFactory() {
                @Override
                public Thread newThread(Runnable r) {
                    Thread t = new Thread(r);
                    t.setUncaughtExceptionHandler((thread, throwable) -> {
                        latch.countDown();
                    });
                    return t;
                }
            });

            // #2 RxJava exception handler
            RxJavaPlugins.setErrorHandler(h -> {
                latch.countDown();
            });

            // #1 observer's onError()
            Flowable.interval(500, TimeUnit.MILLISECONDS, computationScheduler)
                    .subscribe(v -> {
                        throw new OutOfMemoryError();
                    }, e -> {
                        latch.countDown();
                    });

            assertTrue(latch.await(2, TimeUnit.SECONDS));
        } finally {
            RxJavaPlugins.reset();
        }
    }

Sometimes these broken cases matter in certain situation or on certain platform, eg.,
- As Test 1, when out-of-memory occurs before emitter.onComplete(), the application may block forever waiting for onComplete(), because no one in the whole application could possibly known about this exception.
- On Android, on which I code a lot, the exception handing contract implies that any runtime exception or error in any thread should throw to the uncaught exception handler, which will terminate the application. Almost all async tools, including the built in AsyncTask, conform to this contract. Setting an error handler that always throws runtime exceptions and errors via RxJavaPlugins.setErrorHandler() on Android almost makes it. But it doesn't work when schedulers are involved.

The cause is clear. Internal to Scheduler implementation, RxJava only uses Future of a task submitted to Executor as a cancel-handle and never check exceptions inside the Future while any exception thrown by the submitted task will go into the Future.

But the fix is not as easy, there is no chance to check the Future for exception since RxJava pushes task result instead of pulls it.

Pulling results is the design intent of Future. When we won't, I think we should customize the FutureTask which runs the task in Executor and provides the Future function to give us a chance to handle the result(including the exception).  

Actually, JDK has given us all we need to do this via ThreadPoolExecutor#newTaskFor, ScheduledThreadPoolExecutor#decorateTask, RunnableFuture, RunnableScheduledFuture, etc. And Android did something similar in its AsyncTask implementation.

I'll propose a PR that:
- Implements a CompleteScheduledExecutorService which is a ScheduledExecutorService that supports setting a complete handler that will receive the Future(and handle the task result) of the submitted task once it completes in the executing thread.
- Modifies executor based schedulers to use CompleteScheduledExecutorService and check the Future for exceptions(and route it to RxJavaPlugins.onError() or throw it using Exceptions.throwIfFatal()) of submitted tasks in their complete handlers.
- With test cases cover CompleteScheduledExecutorService related code and the above Test 1 & Test 2.

### PR DESCRIPTION
**Pull request by akarnokd**
Fatal exceptions may be lost with scheduled direct & scheduled periodic direct tasks because `FutureTask` simply treats them as exceptional outcomes. For regular tasks, [ScheduledRunnable](https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledRunnable.java#L67) already avoids rethrowing fatal errors as it would go nowhere.

This PR adds this behavior to the direct runnable tasks.

Resolves #6954

### CODE REVIEW

File: src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectPeriodicTask.java [hunk 1]
```diff
@@ -39,7 +38,7 @@ public void run() {
             runnable.run();
             runner = null;
         } catch (Throwable ex) {
-            Exceptions.throwIfFatal(ex);
+            // Exceptions.throwIfFatal(ex); nowhere to go
```
Comment (jxdabc) [inline src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectPeriodicTask.java:41]: But it seems make #748 a problem again. It seems tricky to balance this issue and #748. After all, if we passed StackOverflowError to RxJavaPlugins.onError(), RxJavaPlugins.onError() should throw it and it will be swallowed again.

I think customizing the future task will completely solve #748 and this issue. JDK supports that and at least as I know Android are using that approach. And I think it is not complex as the core code is only implementing the JDK's interface. It even simplifies the schedulers implementation, as I see ; )

**Review by jxdabc — COMMENTED** [review]
I'm sorry, I think I made a mistake.
I'll check it.

**Comment by akarnokd** [comment]
> this will halt the application when stack overflow:

I don't understand. As far as I know, calling the uncaught exception handler on Android kills your app. On desktop, such calls do nothing but the repetition of the `schedulePeriodicallyDirect` should end.

**Comment by jxdabc** [comment]
> > this will halt the application when stack overflow:
> 
> I don't understand. As far as I know, calling the uncaught exception handler on Android kills your app. On desktop, such calls do nothing but the repetition of the `schedulePeriodicallyDirect` should end.

I am sorry. I think I made a mistake when simplifies #748 case. The key point is when StackOverflowError ocurrs calling error hander without throw may cause stack full again. That is also why I selected a complex approach. I'll check it.

**Comment by jxdabc** [comment]
> > this will halt the application when stack overflow:
> 
> I don't understand. As far as I know, calling the uncaught exception handler on Android kills your app. On desktop, such calls do nothing but the repetition of the `schedulePeriodicallyDirect` should end.

Hi, akarnokd, sorry to the above mistake.

Personally,  I think this approach has some flaws.


1 - This approach means we'll catch fatal exceptions instead of throwing it through the call stack. But the functions on the call stack may need this exception to clean/stop itself. For example, this change will make periodic tasks unable to stop (at least on desktop or server):


    @Test // Fail
    public void periodicTaskShouldStopOnError() throws Exception {
        AtomicInteger repeatCount = new AtomicInteger();
        new ComputationScheduler().schedulePeriodicallyDirect(new Runnable() {
            @Override
            public void run() {
                repeatCount.incrementAndGet();
                if (true) {
                    throw new OutOfMemoryError();
                }
            }
        }, 0, 500, TimeUnit.MILLISECONDS);

        Thread.sleep(1000 * 3);
        assertEquals(1, repeatCount.get());
    }


2 - To solve the above problem, we need to rethrow the exception after RxJavaPlugins.onError() or make RxJavaPlugins.onError() to throw after calling the uncaughtExceptionHandler of the thread. This actullay makes some exceptions to be handled more than once. And I think it will make things more and more complex as we solve those cases one by one.

3 - If we are able to check exceptions in the Future as #6954 mentioned (and JDK has given us all we need). Exception handing in RxJava will be simpler and easier as we do elsewhere: make RxJavaPlugins.onError() handle/propagate the exception and continue the work, or make RxJavaPlugins.onError() throws and exceptions go through the stack to do whatever clean/stop needed and finally to the uncaughtExceptionHandler of the thread.

**Comment by jxdabc** [comment]
Disposing the periodic task on error may be a little tricky workaround. 

1 - The periodic FutureTask is canceled asynchronously, until PeriodicDirectTask.setFuture is done. This may cause the periodic task to run some more rounds before actually stop. The following test almost can't success on my laptop:

    @Test
    public void periodicTaskShouldStopOnError() throws InterruptedException {
        try {
            // suppress log
            RxJavaPlugins.setErrorHandler((e) -> {});

            CountDownLatch latch = new CountDownLatch(1000);

            AtomicInteger assertCount = new AtomicInteger();
            for (int i = 0; i < 1000; i++) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            periodicTaskShouldStopOnErrorOnce();
                        } catch (AssertionError e) {
                            e.printStackTrace();
                            assertCount.incrementAndGet();
                        } catch (Exception e) {
                        } finally {
                            latch.countDown();
                        }
                    }
                }).start();
            }

            latch.await();
            assertEquals(0, assertCount.get());
        } finally {
            RxJavaPlugins.reset();
        }
    }

    private void periodicTaskShouldStopOnErrorOnce() throws Exception {
        AtomicInteger repeatCount = new AtomicInteger();

        Schedulers.computation().schedulePeriodicallyDirect(new Runnable() {
            @Override
            public void run() {
                repeatCount.incrementAndGet();
                if (true) {
                    throw new OutOfMemoryError();
                }
            }
        }, 0, 1, TimeUnit.NANOSECONDS);

        Thread.sleep(200);

        assertEquals(1, repeatCount.get());
    }

2 - I wonder whether we should route InterruptibleRunnable's & BooleanRunnable's errors to RxJavaPlugins.onError() as well. If not, I have to handle errors both in RxJavaPlugins.onError() and thread's uncaught exception handlers. When schedulers are involved, errors may be pass to either of the two. 

3 - My original PR was actually intending to make things easy for my team: we only need to set an error handle via RxJavaPlugins.setErrorHandler which prints a log for not-a-matter error and rethrow for fatal erros and every thing goes fine. However, maybe I could replace all schedulers with RxJavaPlugins.setXXXSchedulerHandler without change the main stream though I think my original PR simplifies implemetation of the main stream without side effect as I could see.

**Comment by akarnokd** [comment]
1. Looks like the periodic task should be crashed nonetheless.
2. Yes, task wrapper behavior should be consistent across.
3. "make things easy for my team" - that's why I encourage people to write their own hooks and components to workaround very specific corner cases.

**Comment by jxdabc** [comment]
> 2. Yes, task wrapper behavior should be consistent across.

Would you like to do this in this PR or later?

**Review by jxdabc — APPROVED** [review]

**Review by jxdabc — APPROVED** [review]

**Review by jxdabc — APPROVED** [review]

**Review by jxdabc — APPROVED** [review]

File: src/main/java/io/reactivex/rxjava3/core/Scheduler.java [hunk 2]
```diff
@@ -542,9 +540,10 @@ public void run() {
                 try {
                     run.run();
                 } catch (Throwable ex) {
-                    Exceptions.throwIfFatal(ex);
-                    worker.dispose();
-                    throw ExceptionHelper.wrapOrThrow(ex);
+                    // Exceptions.throwIfFatal(ex); nowhere to go
+                    dispose();
+                    RxJavaPlugins.onError(ex);
+                    throw ex;
```
Comment (akarnokd) [inline src/main/java/io/reactivex/rxjava3/core/Scheduler.java:546]: @JakeWharton Does this syntax work with Android desugar (rethrowing final `Throwable`s)?

Comment (JakeWharton) [reply src/main/java/io/reactivex/rxjava3/core/Scheduler.java:546]: Hmm this looks like a normal throw. I don't understand what might be a compatibility concern here.

Comment (akarnokd) [reply src/main/java/io/reactivex/rxjava3/core/Scheduler.java:546]: The Java 7 compiler feature that let's you rethrow constant cheched or `Throwable` exceptions from within a `catch` block, even if the method didn't specify a `throws` clause.

Comment (JakeWharton) [reply src/main/java/io/reactivex/rxjava3/core/Scheduler.java:546]: Ah, missed it was `Throwable`. Checked exceptions are only a feature of the Java compiler not the Java bytecode so yeah the Android toolchain won't care 👍 .

**Comment by jxdabc** [comment]
Great, that fixed all corner cases I could see.
But I wonder whether calling RxJavaPlugins.onError(ex) (calling uncaught exception handler) in the middle of exception throw chain is good and intuitional. A little tricky as I see.
If you'd have a look on #6955, the original PR. It requires no more change than this one, handling Future related erros in ONE place and not calling uncaught exception handler in the middle of exception throw chain. It should pass all tests in this PR as well without modification. :)
