### PR TITLE
2.x: Fix Generics T[] in Zip & CombineLatest

### LINKED ISSUE #4524: RxJava2 `Observable.zip` taking `Iterable` and a `zipper` is broken
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#zip-java.lang.Iterable-io.reactivex.functions.Function-

The `zipper` signature is `Function<? super T[]>, ? extends R> zipper`, where use of `T[]` breaks it. Just invoke it with non `Object` T, and a `ClassCastException` is thrown.

I checked with `Single` and `Flowable`, they have different signatures for the comparable `zip` operators. They use `Object[]` where `T[]` is used for `Observable`, which are also consistent with the 1.x zip operator.

I think this is just a bug in the signature.

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #4524

Test for combineLatest fill follow

### CODE REVIEW

File: src/test/java/io/reactivex/flowable/FlowableTests.java [hunk 1]
```diff
@@ -1060,4 +1060,19 @@ public void toObservableRange() {
     public void toObservableError() {
         Flowable.error(new TestException()).toObservable().test().assertFailure(TestException.class);
     }
+
+    @Test
+    public void zipIterableObject() {
+        final List<Flowable<Integer>> flowables = Arrays.asList(Flowable.just(1, 2, 3), Flowable.just(1, 2, 3));
+        Flowable.zip(flowables, new Function<Object[], Object>() {
```
Comment (akarnokd) [inline src/test/java/io/reactivex/flowable/FlowableTests.java:1067]: Yeah, this always passes because it is compatible with both `? super T[]` and `? super Object[]`. I have no idea how to test with `Function<Integer[], Object>` because it doesn't even compile with the latter signature. Leave this as is.

File: src/main/java/io/reactivex/Flowable.java [hunk 2]
```diff
@@ -194,7 +194,7 @@ public static int bufferSize() {
      */
     @SchedulerSupport(SchedulerSupport.NONE)
     @BackpressureSupport(BackpressureKind.FULL)
-    public static <T, R> Flowable<R> combineLatest(Function<? super T[], ? extends R> combiner, Publisher<? extends T>... sources) {
+    public static <T, R> Flowable<R> combineLatest(Function<? super Object[], ? extends R> combiner, Publisher<? extends T>... sources) {
```
Comment (vanniktech) [inline src/main/java/io/reactivex/Flowable.java:207]: this one does not seem necessary to be honest. It just has switched arguments with the one above. Or do I oversee anything?

File: src/main/java/io/reactivex/Flowable.java [hunk 3]
```diff
@@ -163,7 +163,7 @@ public static int bufferSize() {
      */
     @SchedulerSupport(SchedulerSupport.NONE)
     @BackpressureSupport(BackpressureKind.FULL)
-    public static <T, R> Flowable<R> combineLatest(Publisher<? extends T>[] sources, Function<? super T[], ? extends R> combiner) {
+    public static <T, R> Flowable<R> combineLatest(Publisher<? extends T>[] sources, Function<? super Object[], ? extends R> combiner) {
```
Comment (akarnokd) [inline src/main/java/io/reactivex/Flowable.java:171]: It might be worth adding a sentence to the javadocs since people tend to ask why this isn't `? super T[]`

```
<p>
Note on method signature: since Java doesn't allow creating a generic array with {@code new T[]}, the 
implementation of this operator has to create an {@code Object[]} instead. Unfortunately, a 
{@code Function<Integer[], R>} passed to the method would trigger a {@code ClassCastException}.
```

If you feel so, you could add these two sentences after the first sentence of all the affected methods and before the marble diagram (as people forget to scroll down below the diagram).

File: src/test/java/io/reactivex/flowable/FlowableTests.java (hunk 1 above)
Comment (vanniktech) [reply src/test/java/io/reactivex/flowable/FlowableTests.java:1067]: Yup `Function<Integer[], Object>` didn't work for me so I didn't add a test case.

File: src/main/java/io/reactivex/Flowable.java (hunk 2 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/Flowable.java:207]: This and other overloads of operators let's you use varargs to specify any number of sources at the expense that varargs has to be the last argument.

File: src/main/java/io/reactivex/Flowable.java (hunk 3 above)
Comment (vanniktech) [reply src/main/java/io/reactivex/Flowable.java:171]: Will do

File: src/main/java/io/reactivex/Flowable.java (hunk 2 above)
Comment (vanniktech) [reply src/main/java/io/reactivex/Flowable.java:207]: Ups right didn't see those little dots there too many overloads ...

File: src/test/java/io/reactivex/maybe/MaybeTest.java [hunk 4]
```diff
@@ -2858,4 +2858,18 @@ public void ambWith2SignalsSuccess() {
         ts.assertResult(2);
     }
 
+    @Test
+    public void zipIterableObject() {
```
Comment (vanniktech) [inline src/test/java/io/reactivex/maybe/MaybeTest.java]: maybe has still no combineLatest operator hence no test for it

**Comment by vanniktech** [comment]
This should be it now

**Comment by akarnokd** [comment]
Single has exactly 1 and Maybe at most 1 item, so there is only 1 latest that can happen thus there is no difference between combineLatest and zip for these sources.

**Comment by akarnokd** [comment]
:+1:

**Comment by vanniktech** [comment]
Yup I immediately noticed it after I wrote my comment :D that's also why I deleted it
