### PR TITLE
Fixes wrong request accounting in AbstractOnSubscribe

### LINKED ISSUE #2853: AbstractOnSubscribe throws exception when onNext contains a request for more
```AbstractOnSubscribe``` improperly throws an exception when the ```onNext``` method in a subscriber makes a call to ```request``` (all calls synchronous). The error thrown is this:

```
java.lang.IllegalStateException: This is not reentrant nor threadsafe!
	at rx.observables.AbstractOnSubscribe$SubscriptionState.use(AbstractOnSubscribe.java:590)
	at rx.observables.AbstractOnSubscribe$SubscriptionProducer.doNext(AbstractOnSubscribe.java:360)
	at rx.observables.AbstractOnSubscribe$SubscriptionProducer.request(AbstractOnSubscribe.java:345)
	at rx.Subscriber.request(Subscriber.java:145)
	at rx.observables.AbstractOnSubscribeTest$20.onNext(AbstractOnSubscribeTest.java:541)
	at rx.observables.AbstractOnSubscribeTest$20.onNext(AbstractOnSubscribeTest.java:1)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
	at rx.observables.AbstractOnSubscribe$SubscriptionState.accept(AbstractOnSubscribe.java:533)
	at rx.observables.AbstractOnSubscribe$SubscriptionProducer.doNext(AbstractOnSubscribe.java:367)
	at rx.observables.AbstractOnSubscribe$SubscriptionProducer.request(AbstractOnSubscribe.java:337)
	at rx.Subscriber.setProducer(Subscriber.java:175)
	at rx.Subscriber.setProducer(Subscriber.java:171)
	at rx.observables.AbstractOnSubscribe.call(AbstractOnSubscribe.java:191)
	at rx.observables.AbstractOnSubscribe.call(AbstractOnSubscribe.java:1)
	at rx.Observable.subscribe(Observable.java:7585)
	at rx.observables.AbstractOnSubscribeTest.testCanRequestInOnNext(AbstractOnSubscribeTest.java:527)
```

Here's a failing unit test:

```java
    @Test
    public void testCanRequestInOnNext() {
        AbstractOnSubscribe<Integer, Void> aos = new AbstractOnSubscribe<Integer, Void>() {
            @Override
            protected void next(SubscriptionState<Integer, Void> state) {
                state.onNext(1);
                state.onCompleted();
            }
        };
        final AtomicReference<Throwable> exception = new AtomicReference<Throwable>();
        aos.toObservable().subscribe(new Subscriber<Integer>() {

            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {
                exception.set(e);
            }

            @Override
            public void onNext(Integer t) {
                request(1);
            }
        });
        if (exception.get()!=null)
            exception.get().printStackTrace();
        assertNull(exception.get());
    }
```

### PR DESCRIPTION
**Pull request by akarnokd**
Fixes #2853.

### CODE REVIEW

File: src/main/java/rx/observables/AbstractOnSubscribe.java [hunk 1]
```diff
@@ -332,20 +332,22 @@ private SubscriptionProducer(SubscriptionState<T, S> state) {
...
         @Override
         public void request(long n) {
-            if (n == Long.MAX_VALUE) {
-                for (; !state.subscriber.isUnsubscribed(); ) {
-                    if (!doNext()) {
-                        break;
-                    }
-                }
-            } else 
             if (n > 0 && state.requestCount.getAndAdd(n) == 0) {
```
Comment (davidmoten) [inline src/main/java/rx/observables/AbstractOnSubscribe.java]: Use BackpressureUtils.getAndAdd here to avoid request overflow?

Comment (akarnokd) [inline src/main/java/rx/observables/AbstractOnSubscribe.java]: Thanks. I thought I added it because of the visibility changes, but it appears it got lost somewhere.

File: src/main/java/rx/observables/AbstractOnSubscribe.java [hunk 2]
```diff
@@ -332,20 +333,22 @@ private SubscriptionProducer(SubscriptionState<T, S> state) {
...
-                    if (!doNext()) {
-                        break;
-                    }
-                }
-            } else 
-            if (n > 0 && state.requestCount.getAndAdd(n) == 0) {
-                if (!state.subscriber.isUnsubscribed()) {
-                    do {
+            if (n > 0 && BackpressureUtils.getAndAddRequest(state.requestCount, n) == 0) {
+                // fast-path
```
Comment (davidmoten) [inline src/main/java/rx/observables/AbstractOnSubscribe.java]: move this comment down a line (inside the next if block) for clarity?

File: src/main/java/rx/observables/AbstractOnSubscribe.java [hunk 3]
```diff
@@ -332,20 +333,22 @@ private SubscriptionProducer(SubscriptionState<T, S> state) {
...
+                if (n == Long.MAX_VALUE) {
+                    for (; !state.subscriber.isUnsubscribed(); ) {
                         if (!doNext()) {
                             break;
                         }
-                    } while (state.requestCount.decrementAndGet() > 0 && !state.subscriber.isUnsubscribed());
+                    }
+                } else {
```
Comment (davidmoten) [inline src/main/java/rx/observables/AbstractOnSubscribe.java]: maybe chuck the {} so that it reads ```else if {}``` instead of ```else { if {} }```?

**Comment by davidmoten** [comment]
LGTM beyond trivial changes mentioned above. Thanks @akarnokd for fixing quickly (as usual)!

**Comment by akarnokd** [comment]
Done.
