### PR TITLE
2.x: distinguish between sync and async dispose in ScheduledRunnable

### LINKED ISSUE #5711: Premature thread interruption when using observeOn operator
When using RxJava 2.1.3 to 2.1.6, we observed a possible racing condition which caused the observeOn thread to be interrupted prematurely.

A sample code snippet could be the following (not a complete example):
```java
Observable.fromPublisher(publisher)
.observeOn(Schedulers.computation())
.firstElement()
.map(operation)
.blockingGet();
```

In the above example, observeOn operator would create a ObservableObserveOn instance. When there is the first item coming (ObservableObserveOn.ObserveOnObserver.onNext() is called), a Runnable is scheduled via the NewThreadWorker.scheduleActual(). Inside NewThreadWorker.scheduleActual(), a ScheduledRunnable is created wrapping the given Runnable, and submit the ScheduledRunnable to the executor for execution. Then the future returned by the executor is set into ScheduledRunnable via setFuture method.

The problem lies when the ScheduledRunnable.dispose() method is called between submitting to the executor and ScheduledRunnable.setFuture method by the underlying Runnable wrapped in ScheduledRunnable (which is executed in parallel by the executor). In this case, the Runnable contains the firstElement() operator would create a ObservableElementAtMaybe instance. ObservableElementAtMaybe.onNext() method would call the dispose() method before calling actual.onSuccess(). So combining these, if ScheduledRunnable.setFuture is called after ScheduledRunnable.dispose() in ObservableElementAtMaybe.onNext(), the actual.onSuccess() would be interrupted, which is not what we want.

**tl;dr** In the sample code, if the execution order is the following, it would create a thread interruption that interfere with the processing of the chained operators.
```
Thread 1: future = executor.submit(ScheduledRunnable)
Thread 2 (executor thread): ScheduledRunnable.dispose()
Thread 1: ScheduledRunnable.setFuture(future)
Thread 2: actual callback (e.g. actual.onSuccess()) <-- Thread interrupted. Throws exception when we call some synchronization methods in a non-blocking way (e.g. Semaphore.tryAcquire(0, TimeUnit.SECONDS)). 
```

A possible solution is to change the order, i.e. call actual.onSuccess() before dispose(). I searched the code base and found out that in general, dispose() is called before the actual callback. I am not sure if there are other concerns with this specific ordering (i.e. dispose before actual callback), but it certainly sounds odd to me.

### PR DESCRIPTION
**Pull request by akarnokd**
This PR adds logic to distinguish between synchronous and asynchronous dispose calls when `setFuture` is executing. It should prevent interrupting the currently running task body if it requested cancellation indirectly before the `setFuture` was executed by the Thread which scheduled the task.

Fixes #5711

### CODE REVIEW

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java [hunk 1]
```diff
@@ -26,7 +26,12 @@
     private static final long serialVersionUID = -6120223772001106981L;
     final Runnable actual;
 
-    static final Object DISPOSED = new Object();
+    /** Indicates that the parent tracking this task has been notified about its completion. */
+    static final Object PARENT_DISPOSED = new Object();
+    /** Indicates the dispose() was called from within the run/call method. */
+    static final Object SYNC_DISPOSED = new Object();
+    /** Indicates the dispose() was called from another thread. */
+    static final Object ASYNC_DISPOSED = new Object();
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:34]: supernit: `ASYNC` doesn't mean another thread :)

But for name conciseness I guess it's fine

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java [hunk 2]
```diff
@@ -66,13 +71,13 @@ public void run() {
         } finally {
             lazySet(THREAD_INDEX, null);
             Object o = get(PARENT_INDEX);
-            if (o != DISPOSED && o != null && compareAndSet(PARENT_INDEX, o, DONE)) {
+            if (o != PARENT_DISPOSED && compareAndSet(PARENT_INDEX, o, DONE) && o != null) {
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:74]: Change of `compareAndSet` position in `if` statement seems to be a behavior change…

Though it doesn't affect `ScheduledRunnableTest` on my machine

Do we need that change?

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java [hunk 3]
```diff
@@ -99,23 +108,24 @@ public void setFuture(Future<?> f) {
     public void dispose() {
         for (;;) {
             Object o = get(FUTURE_INDEX);
-            if (o == DONE || o == DISPOSED) {
+            if (o == DONE || o == SYNC_DISPOSED || o == ASYNC_DISPOSED) {
                 break;
             }
-            if (compareAndSet(FUTURE_INDEX, o, DISPOSED)) {
+            boolean async = get(THREAD_INDEX) != Thread.currentThread();
+            if (compareAndSet(FUTURE_INDEX, o, async ? ASYNC_DISPOSED : SYNC_DISPOSED)) {
```
Comment (artem-zinnatullin) [inline src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:115]: Hm, what worries me here is that we base `boolean async` on `get(THREAD_INDEX) != Thread.currentThread()`, but in `finally` of `run()` we set `Thread` to null which always gonna give `async == false` 

https://github.com/ReactiveX/RxJava/blob/b99efbfb71d3a76befccd4e36324cefadeefd65a/src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java#L67

Yes, it's `lazySet()`, but aren't we creating unwanted race condition here between `run()` and `dispose()`?

The worst scenario is that if `dispose()` indeed was called from another thread but `lazySet()` memory write becomes visible to it, we'll have `async == false` which is actually wrong in this scenario…

**Review by artem-zinnatullin — COMMENTED** [review]
LGTM, but comments

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java (hunk 2 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:74]: Yes. With the previous order, if `o` was `null` because of lack of a parent, the CAS didn't happen and the task would partially appear to be still active. With the sync-async marker changes, `isDisposed` was switched to check the parent reference for indication of being disposed instead of the future reference, which required now 3 comparisons instead of 2.

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java (hunk 3 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:115]: Cancelling from the current thread could only happen while the `run` callback is executing. Any other cancellation that comes after this can only be asynchronous. It doesn't matter what value is in `THREAD_INDEX` at this time because that will not be the same thread as the caller's. 

Since we are running with single-threaded thread pools, any subsequent task on the same pool having the same Thread will find the references marked as `DONE` and not cancel the previous task. This is guaranteed by the sequential task processing of the thread pool.

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java (hunk 2 above)
Comment (artem-zinnatullin) [reply src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:74]: Makes sense, can you please add a test to cover that then? 

When I changed order back to original one on your branch, whole `ScheduledRunnableTest` passed

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java (hunk 3 above)
Comment (artem-zinnatullin) [reply src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:115]: >It doesn't matter what value is in THREAD_INDEX at this time because that will not be the same thread as the caller's.

Aha, I see now, 👍

**Review by artem-zinnatullin — APPROVED** [review]

File: src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java (hunk 2 above)
Comment (akarnokd) [reply src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:74]: Sure.

Comment (akarnokd) [reply src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java:74]: Unit tests added.

**Review by artem-zinnatullin — APPROVED** [review]

**Review by vanniktech — APPROVED** [review]
