### PR TITLE
2.x: Fix Completable.andThen(Completable) not running on observeOn scheduler.

### LINKED ISSUE #6354: 2.2.5: observeOn might not work for Completable.andThen(Completable)
- RxJava 2.2.5

It seems that Completable passed to `Completable.andThen(...)` is not run on scheduler passed to observeOn. So
```
        Completable.fromAction(() -> System.out.println("subscribing in thread " + Thread.currentThread().getName()))
                .observeOn(Schedulers.io())
                .andThen(Completable.fromAction(() -> System.out.println("and then in thread " + Thread.currentThread().getName())))
                .subscribe(() -> System.out.println("observing in thread " + Thread.currentThread().getName()));
```
might produce
```
subscribing in thread main
and then in thread main
observing in thread main
```
I don't know if it's by design or not, but it seems to be caused by 'race condition' in `CompletableConcatArray` where we have do {...} while() loop, when next() method is run second time from io() thread and bumps up the atomic counter, and then second iteration of do/while loop starts, and executes completable from andThen operator from main thread. It can be easily reproduced if you add some work to that loop before checking condition in while clause so in `CompletableConcatArray`:
```
                a[idx].subscribe(this);
                // spin the cpu for a while to make ObserveOnCompletable run this next() method
                int i = 0, j = 0;
                while (i < 1000_000) {
                    i++;
                    while (j < 1000_000) {
                        j++;
                    }
                }
            } while (decrementAndGet() != 0);
```

### PR DESCRIPTION
**Pull request by pjastrz**
This PR fixes unpredictable scheduler/thread used by `Completable.observeOn(...)andThen(Completable)`, since sometimes scheduler defined in observeOn(...) was not used. It was inconsistent with similar `.andThen(Maybe)` and `.andThen(Single)`, since those are guaranteed to run second Completable using proper scheduler if defined with `.observeOn`.
Fixes: https://github.com/ReactiveX/RxJava/issues/6354.

### CODE REVIEW

File: src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenCompletableabTest.java [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+        Completable.complete()
+                .andThen(Completable.complete())
+                .test()
+                .assertComplete();
+    }
+
+    @Test
+    public void andThenCompletableCompleteError() {
+        Completable.complete()
+                .andThen(Completable.error(new RuntimeException("test")))
```
Comment (akarnokd) [inline src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenCompletableabTest.java]: Please use `TestException` so we don't mistake them with any other `RuntimeException` failures.

File: src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenTest.java [hunk 2]
```diff
@@ -69,39 +63,4 @@ public void andThenMaybeError() {
             .assertError(RuntimeException.class)
             .assertErrorMessage("bla");
     }
-
-    @Test
-    public void andThenNoInterrupt() throws InterruptedException {
```
Comment (akarnokd) [inline src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenTest.java:74]: Why was this test removed without explanation?

**Review by akarnokd — CHANGES_REQUESTED** [review]

File: src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenTest.java (hunk 2 above)
Comment (pjastrz) [reply src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenTest.java:74]: I moved it to CompletableAndThenCompletableTest since it specifically tested `.andThen(Completable)`.

File: src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenCompletableabTest.java (hunk 1 above)
Comment (pjastrz) [reply src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenCompletableabTest.java]: Ok, done.

**Review by akarnokd — APPROVED** [review]

**Review by vanniktech — APPROVED** [review]
